const SET_REQUESTS = '@REQUESTS.SET_REQUESTS'
const SET_SELECTED_REQUEST = '@REQUESTS.SET_SELECTED_REQUEST'
const SET_POINTS_OF_SALES = '@PROFILES_AND_ACCESS.SET_POINTS_OF_SALES'
const SET_POINTS_OF_SALES_MVP = '@PROFILES_AND_ACCESS.SET_POINTS_OF_SALES_MVP'
const SET_SELECTED_POINTS_OF_SALES =
  '@PROFILES_AND_ACCESS.SET_SELECTED_POINTS_OF_SALES'
const SET_USERS_MVP = '@PROFILES_AND_ACCESS.SET_USERS_MVP'
const SET_USER_DATA = '@USER.SET_USER_DATA'
const CLEAR_USER_DATA = '@USER.CLEAR_USER_DATA'
const SET_SELECTED_USER = '@USER.SET_SELECTED_USER'
const SET_APPLICATION_SELECTED_IN_USERS =
  '@USERS.SET_APPLICATION_SELECTED_IN_USERS'
const SET_APPLICATIONS = '@APPLICATIONS.SET_APPLICATIONS'
const SET_APPLICATION_SELECTED = '@APPLICATIONS.SET_APPLICATION_SELECTED'
const SET_USERS_BIS = '@USERS.SET_USERS_BIS'
const SET_ROLES = '@ROLES.SET_ROLES'
const SET_PERMISSIONS = '@ROLES.SET_PERMISSIONS'
const SET_TAB = '@TABS.SET_TAB'

export {
  SET_REQUESTS,
  SET_POINTS_OF_SALES,
  SET_USERS_MVP,
  SET_USER_DATA,
  CLEAR_USER_DATA,
  SET_APPLICATIONS,
  SET_APPLICATION_SELECTED,
  SET_USERS_BIS,
  SET_SELECTED_REQUEST,
  SET_SELECTED_POINTS_OF_SALES,
  SET_POINTS_OF_SALES_MVP,
  SET_ROLES,
  SET_PERMISSIONS,
  SET_SELECTED_USER,
  SET_APPLICATION_SELECTED_IN_USERS,
  SET_TAB,
}
